- name: system setup Ensure public DNS entries exist in /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: "{{ item }}"
    state: present
    insertafter: EOF
  loop:
    - "nameserver 8.8.8.8"
    - "nameserver 8.8.4.4"

- name: Clean Yum metadata
  command: yum clean all

- name: Clean yum metadata and rebuild cache (CentOS 7 only)
  ansible.builtin.shell: |
    yum clean metadata
    yum makecache
  args:
    warn: false
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

#- name: Run yum update using shell
#  ansible.builtin.shell: yum -y update
#  args:
#    warn: false

- name: Run yum update with error tolerance
  shell: yum -y update || echo "Yum update failed"
  register: update_result
  ignore_errors: yes

- name: Print yum update result
  debug:
    var: update_result.stdout_lines

- name: Copy required repos to AWS EC2 Instance
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: root
    group: root
  register: copy_repo_files
  loop:
    - { src: 'almalinux.repo', dest: '/etc/yum.repos.d' }

- name: system setup Install required dependencies
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
