---
- name: Install EFS(NFS) client (nfs-utils)
  become: yes
  package:
    name: nfs-utils
    state: present

- name: Create EFS mount directory
  become: yes
  file:
    path: /mnt/efs
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Mount EFS to /mnt/efs
  become: yes
  mount:
    path: /mnt/efs
    src: "{{ efs_dns_name }}:/"
    fstype: nfs4
    opts: "_netdev"
    state: mounted
